### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by h3ndro** [botman/driver-slack#22]
install botman driver-slack

Laravel: 5.5
Botman: 2.1
====================================================
root@b70a25ba300a:/var/www/html/ombot# composer require botman/driver-slack

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Using version ^1.1 for botman/driver-slack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install botman/driver-slack 1.1.3
    - Conclusion: don't install botman/driver-slack 1.1.2
    - Conclusion: don't install botman/driver-slack 1.1.1
    - Conclusion: remove evenement/evenement v3.0.1
    - Installation request for botman/driver-slack ^1.1 -> satisfiable by botman/driver-slack[1.1.0, 1.1.1, 1.1.2, 1.1.3].
    - Conclusion: don't install evenement/evenement v3.0.1
    - botman/driver-slack 1.1.0 requires mpociot/slack-client 0.3.* -> satisfiable by mpociot/slack-client[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4].
    - mpociot/slack-client 0.3.0 requires evenement/evenement 2.0.* -> satisfiable by evenement/evenement[v2.0.0].
    - mpociot/slack-client 0.3.1 requires evenement/evenement 2.0.* -> satisfiable by evenement/evenement[v2.0.0].
    - mpociot/slack-client 0.3.2 requires evenement/evenement 2.0.* -> satisfiable by evenement/evenement[v2.0.0].
    - mpociot/slack-client 0.3.3 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - mpociot/slack-client 0.3.4 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v2.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.1.0, v3.0.1].
    - Installation request for evenement/evenement (locked at v3.0.1) -> satisfiable by evenement/evenement[v3.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by mollierobbert** [comment]
Installing the driver first before installing `botman/botman` fixed the issue for me. Still an issue though.

**Comment by mpociot** [comment]
Fixed with version 2.0, that adds support for evenement 3.x
