### ISSUE TITLE
Issue with composer dependencies 

### ISSUE THREAD

**Issue by bbrala** [botman/driver-slack#34]
From what i read i need to include `mpociot/slack-client`, but that package requires `react/event-loop` in the 0.4 range which conflicts with botman. Is that slack client maintained by you guys?

**Comment by marcinj1** [comment]
I'm facing this same problem

**Comment by bbrala** [comment]
I ended up now using the RTM client, which means you don't need that package.

**Comment by JurRutten** [comment]
Could you elaborate how you fixed this?

**Comment by bbrala** [comment]
Just don't include `mpociot/slack-client`, it works kinda fine without that.
