### ISSUE TITLE
Get requirements error when trying to install slack driver

### ISSUE THREAD

**Issue by mhetreramesh** [botman/driver-slack#37]
I get following error for command `php artisan botman:install-driver slack`:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - botman/driver-slack 2.1.3 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0, 1.1] but these conflict with your requirements or minimum-stability.
>     - botman/driver-slack 2.1.2 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0, 1.1] but these conflict with your requirements or minimum-stability.
>     - botman/driver-slack 2.1.1 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0, 1.1] but these conflict with your requirements or minimum-stability.
>     - botman/driver-slack 2.1.0 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0, 1.1] but these conflict with your requirements or minimum-stability.
>     - Installation request for botman/driver-slack ^2.1 -> satisfiable by botman/driver-slack[2.1.0, 2.1.1, 2.1.2, 2.1.3].

**Comment by mhetreramesh** [comment]
I'm able to install it with latest version of PHP & studio. Thanks anyway!

**Comment by vesper8** [comment]
this problem continues to this day.. the way I got around it is by uninstalling botman, then installing the slack driver, first, and then installing botman again
